### ISSUE TITLE
Could you provide the steps for Tensorflow BERT INT8 Inference?

### ISSUE THREAD

**Issue by shuangpe** [IntelAI/models#107]
We want to run Tensorflow BERT INT8 inference, but the link [Tensorflow BERT INT8 Inference](https://github.com/IntelAI/models/blob/master/benchmarks/language_modeling/tensorflow/bert_large/inference/int8/README.md) is invalid.

**Comment by dmsuehir** [comment]
@shuangpe  BERT large int8 inference isn't supported yet. We'll remove the link. Thanks
