### ISSUE TITLE
Where can I get model file ssd_resnet34_bs1.pb

### ISSUE THREAD

**Issue by ghost** [IntelAI/models#17]
Where can I get model file ssd_resnet34_bs1.pb?

**Comment by dmsuehir** [comment]
@kubowuhao The pretrained model for SSD-ResNet 34 has been posted here: `https://storage.googleapis.com/intel-optimized-tensorflow/models/ssd_resnet34_fp32_bs1_pretrained_model.pb`. The README file will be updated with this link in our next release. 

Thanks!

**Comment by dmsuehir** [comment]
@kubowuhao Has your issue been resolved?

**Comment by dmsuehir** [comment]
Closing this issue, since the pretrained model file has been provided and the SSD-ResNet34 README was updated with the link.
https://github.com/IntelAI/models/blob/master/benchmarks/object_detection/tensorflow/ssd-resnet34/README.md
