### ISSUE TITLE
403 downloading ResNet50 models

### ISSUE THREAD

**Issue by WarrenSchultz** [IntelAI/models#175]
https://github.com/IntelAI/models/tree/master/models_v2/tensorflow/resnet50v1_5/inference/gpu

Neither of these commands download a file successfully.
```
# For int8:
wget https://storage.googleapis.com/intel-optimized-tensorflow/models/3_1/resnet50_v1_int8.pb

# For float32, tensorflow32, float16 and bfloat16:
wget https://storage.googleapis.com/intel-optimized-tensorflow/models/3_1/resnet50_v1.pb
```

**Comment by sramakintel** [comment]
@WarrenSchultz , thanks for reaching out. the error has been fixed. Can you try again?

**Comment by WarrenSchultz** [comment]
> @WarrenSchultz , thanks for reaching out. the error has been fixed. Can you try again?

That did the job, thank you!
