### ISSUE TITLE
Scripts for BERT Large Training Not Found on Master Branch

### ISSUE THREAD

**Issue by mins2022** [IntelAI/models#176]
https://github.com/IntelAI/models/blob/master/quickstart/language_modeling/pytorch/bert_large/training/gpu/DEVCATALOG.md

Unable to find the two script files named 'bf16_training_plain_format.sh' and 'ddp_bf16_training_plain_format.sh' on the master branch.

**Comment by Prabhuguru21** [comment]
Hey! looks like training/gpu - multiple files are deleted by mistake. Can you revert the change and publish prevision version. Currently no scripts are available in this path.

**Comment by Prabhuguru21** [comment]
@Mahathi-Vatsal  Can you revert this please ?? Need these scripts for training

**Comment by Mahathi-Vatsal** [comment]
Here are the bert_large training scripts: https://github.com/IntelAI/models/blob/master/models_v2/pytorch/bert_large/training/gpu/README.md

The path have changed. The correct path is mentioned in the main README.md as well: https://github.com/IntelAI/models?tab=readme-ov-file#intel-data-center-gpu-workloads

**Comment by Mahathi-Vatsal** [comment]
Here are the bert_large training scripts: https://github.com/IntelAI/models/blob/master/models_v2/pytorch/bert_large/training/gpu/README.md

The path have changed. The correct path is mentioned in the main README.md as well: https://github.com/IntelAI/models?tab=readme-ov-file#intel-data-center-gpu-workloads
