### ISSUE TITLE
The scripts didn;t provide "--steps" parameters out 

### ISSUE THREAD

**Issue by Leslie-Fang** [IntelAI/models#20]
Hi,
I am running RN50 workloads, and I want to set the "--steps=1000" parameter with the scripts of 
models/benchmarks/launch_benchmark.py
My command would be:
python models/benchmarks/launch_benchmark.py --in-graph /root/rsn50_frozen_max_min.pb --model-name resnet50 --framework tensorflow --precision int8 --mode inference --batch-size=1 --socket-id 0 --benchmark-only --docker-image tensorflow/tensorflow-estimator:latest-mkl --data-location /root/tensorflow/dataset/TF_Imagenet_FullData --num-inter-threads=1 --num-intra-threads=26 --steps=1000

The "--steps" parameter doesn't work.
And I have to modified the function "add_steps_args()" in the "benchmarks/common/tensorflow/start.sh” script

**Comment by Leslie-Fang** [comment]
Need to add this parameter:
--warmup_steps=50 steps=500

**Comment by karthikvadla** [comment]
There should be `space` between `--` and `warmup_steps`. These are extra args to the model so should be given at the end with `--` and space. Please see below example

```
python launch_benchmark.py \
    --in-graph /home/<user>/resnet50_int8_pretrained_model.pb \
    --model-name resnet50 \
    --framework tensorflow \
    --precision int8 \
    --mode inference \
    --batch-size=128 \
    --benchmark-only \
    --docker-image intelaipg/intel-optimized-tensorflow:PR25765-devel-mkl
    -- warmup_steps=50 steps=500
```
