### ISSUE TITLE
About the OPM_NUM_THREADS

### ISSUE THREAD

**Issue by luvclear** [IntelAI/models#22]
i tried to change OMP_NUM_THREADS to determine how it would affect the CPU performance
by changing EXPORT OMP_NUM_THREADS='' 
however the outcome seemed to be unchanged, and i found the follow in the information:
User settings:
   KMP_AFFINITY=granularity=fine,verbose,compact,1,0
   KMP_BLOCKTIME=1
   KMP_SETTINGS=1
   OMP_NUM_THREADS=16

the OMP_NUM_THREADS never change 
so how can i change it?

**Comment by karthikvadla** [comment]
Are you trying to use `launch_benchmark.py` script??? IF so, use something like below
```
python launch_benchmark.py \
    --in-graph /home/<user>/resnet50_int8_pretrained_model.pb \
    --model-name resnet50 \
    --framework tensorflow \
    --precision int8 \
    --mode inference \
    --batch-size=128 \
    --benchmark-only \
    --docker-image intelaipg/intel-optimized-tensorflow:PR25765-devel-mkl
    -- warmup_steps=50 steps=500 OMP_NUM_THREADS=<your_value>
```

**Comment by dmsuehir** [comment]
@luvclear Did Karthik's response resolve your issue with being able to set the env vars?
