### ISSUE TITLE
Bazel Build fails on Ubuntu 16.04 - No such target log_severity

### ISSUE THREAD

**Issue by mohammedayub44** [IntelAI/models#37]
Hi,

I'm trying to build the the Intel Optimized Binaries for Tensorflow Serving on my Ubuntu 16.04 machine.  I ran into the below error  `no such target '@com_google_absl//absl/base:log_severity'`

![image](https://user-images.githubusercontent.com/7122670/62952964-a6b5a680-bdba-11e9-82fb-2adc269f4e17.png)

I'm running the below command - 
`docker build -t $USER/tensorflow-serving-devel-mkl -f /home/ubuntu/serving/tensorflow_serving/tools/docker/Dockerfile.devel-mkl2 .`

The only thing I have changed in the docker file is the base image to be 16.04 instead of 18.04

Is there anything I'm missing ?

Thanks!

**Comment by ashahba** [comment]
Hi @mohammedayub44 thanks for filing this issue.
A lot has changed since you filed this.
Would you let us know if this works now? By the way our supported OS is `Ubuntu 18.04` as of now.
