### ISSUE TITLE
Incorrect type specified in Object Detection Tutorial

### ISSUE THREAD

**Issue by athun001** [IntelAI/models#42]
Object Detection with SSD-VGG16

Replace os.environ["OMP_NUM_THREADS"]= 11
with os.environ["OMP_NUM_THREADS"]= "11"

**Comment by ashahba** [comment]
Hi @athun001 thanks for filing this issue.

The `SSD-VGG16` is no longer supported in our main branch and the current references of `OMP_NUM_THREADS` don't seem to have that issue.

Feel free to review and close this ticket if that is the cose.
