### ISSUE TITLE
dead code and ignored cli option for framework in launch_benchmark.py

### ISSUE THREAD

**Issue by kkasravi** [IntelAI/models#44]
when trying to run w/o docker (bare-metal) the method run_bare_metal has this code
```        
        # To Launch Tensorflow Serving benchmark we need only --in-graph arg.
        # It does not support checkpoint files.
        if args.framework == "tensorflow_serving":
```
which can't be entered because validate_args rejects -f tensorflow_serving

**Comment by ashahba** [comment]
@kkasravi Thanks for filing this.

`TensorFlow Serving` is re-enabled again with `v1.8.0` release.
Feel free to update and close the ticket if this is no longer an issue with `v1.8.0` and newer releases.
