### ISSUE TITLE
Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA

### ISSUE THREAD

**Issue by zqyjixiang** [IntelAI/models#48]
Hi,
I followed the instructions in [Wide & Deep](https://github.com/IntelAI/models/tree/master/benchmarks/recommendation/tensorflow/wide_deep_large_ds) and run test successfully, but saw below messages:

```
I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
```

Is this correct behavior or tf bug? 
I have tried *pip install intel-tensorflow==1.15* and didn't see this message. The instructions in  [Wide & Deep](https://github.com/IntelAI/models/tree/master/benchmarks/recommendation/tensorflow/wide_deep_large_ds) used intel-tensorflow==2.1.0, does this matter?

**Comment by zqyjixiang** [comment]
BTW, inner docker, I double confirmed with below command, as it said, MKL was enabled. Looks something wrong for the confusing message. 
This model zoo is really nice. Please check it. Thanks a lot. 
![image](https://user-images.githubusercontent.com/19850328/80080970-ea38f500-8584-11ea-8cc9-15e0a63fa304.png)

**Comment by ashahba** [comment]
For backward compatibility we build our containers with only `avx`. For now I'd just ignore those warnings.

Our team is in the process releasing `avx512` images, so the warning should go aways after TensorFlow `v2.3` release.

**Comment by louie-tsai** [comment]
Hi 
There is also an old issue related to this question, and I put the link below for your reference.
https://github.com/IntelAI/models/issues/62

Overall, Intel Tensorflow will leverage oneDNN(MKL-DNN) for major DL operations, and oneDNN use JIT kernel to generate the best kernels for you.

If you enable oneDNN verbose log, you can actually see whether you use the AVX512 or AVX2 for your models.

Here are two tutorials for your reference.
https://github.com/oneapi-src/oneAPI-samples/blob/master/Libraries/oneDNN/tutorials/tutorial_verbose_jitdump.ipynb
https://github.com/oneapi-src/oneAPI-samples/blob/master/Libraries/oneDNN/tutorials/tutorial_analyze_isa_with_dispatcher_control.ipynb

regards
