### ISSUE TITLE
Distributed Training for FP32 Resnet50_v1.5 exited on signal 11 (Segmentation fault)

### ISSUE THREAD

**Issue by priyankasebastian** [IntelAI/models#61]
Job was launched outside the container with the following environment setup: centos7  ,openmpi 3.1.4 ,intel-tensorflow2.1.0 , horovod==0.19.5 on a Python3.6 virtual environment.  ( Same setup worked for Int8 and FP32 inference). However, Distributed training is exiting with Segmentation fault. Is this a known issue?

Attaching full log here:
[benchmark_resnet50v1_5_training_fp32_20200812_143606.log](https://github.com/IntelAI/models/files/5067412/benchmark_resnet50v1_5_training_fp32_20200812_143606.log)

**Comment by ashahba** [comment]
@priyankasebastian Thanks for reporting this.
We are looking into it.

**Comment by Kmannth** [comment]
@ashahba 

We were able to run for over 10 hours without issue with:
Intel Model Zoo 1.8.0 
OpenMpi 1.10.7
Intel TensorFlow 2.2 
Intel Python 3 2020.2-902
Horovod 1.19.5 

It seems like we have passed this segfault issue.

**Comment by ashahba** [comment]
Thanks @Kmannth for the update.

By the way we just released `v1.8.1` which support TensorFlow `v2.3`.
@priyankasebastian Please let me know if this is still an issue for you, otherwise feel free to close the ticket.

Thanks.

**Comment by priyankasebastian** [comment]
Thankyou @ashahba for the quick response and help. This issue was resolved when we switched to newer release:
Intel Model Zoo 1.8.0 
OpenMpi 1.10.7
Intel TensorFlow 2.2
