### ISSUE TITLE
The latest docker image was not compiled to use AVX2 AVX512F FMA

### ISSUE THREAD

**Issue by zhao1157** [IntelAI/models#62]
I pulled the latest tensorflow image `docker pull intel/intel-optimized-tensorflow`, and found the following meassage at the beginning of running a script:

`2020-08-18 08:52:56.002977: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA`

Through some research, it seems the only way to work around this is to rebuild tensorflow. Is there a better way of fixing this issue in the docker image? Or will this have a negative impact on the performance?

**Comment by wei-v-wang** [comment]
A subset of the released docker containers were compiled to use AVX512.
Can you try: intel/intel-optimized-tensorflow:tensorflow-2.2-bf16-rn50-nightly? 
It works for FP32 as well.

**Comment by zhao1157** [comment]
@wei-v-wang Thanks for your suggestion. Later I found this [https://www.intel.com/content/www/us/en/artificial-intelligence/posts/improving-tensorflow-inference-performance-on-intel-xeon-processors.html](url), which says 

> Intel MKL-DNN will detect and utilize all available CPU instructions, regardless of what compiler flags TensorFlow has been built with.

So it sounds like I can just neglect that compiling message. Right?

**Comment by wei-v-wang** [comment]
@zhao1157  Yes, the compiling message only affects the portions of code that are not running with oneDNN (previously called Intel MKL-DNN).
