### ISSUE TITLE
How does TensorFlow handle the situation of running a training with BF16 on a CPU which does not support it?

### ISSUE THREAD

**Issue by zhao1157** [IntelAI/models#64]
I compared the performance of training with `fp32` and `bf16` on a CPU which does not support `bf16`. Interestingly, the training managed to finish with `bf16`, though the performance was much worse than `fp32`. I also did a similar test for `fp16`, whose performance was also worse than `fp32`. Since the CPU does not support `fp16` or `bf16`, I am very interested to know how TensorFlow handles such situation.

**Comment by claynerobison** [comment]
@agramesh1  or @wei-v-wang can you comment here?

**Comment by agramesh1** [comment]
Native BF16 is only available in the 3rd Gen Xeon scalable (Cooperlake), on previous generations processors (with AVX512) it is supported through AVX512 instructions and the performance will be much lower than FP32.  It mainly intended for development purposes.

**Comment by zhao1157** [comment]
Thank you very much for your comment.

**Comment by wei-v-wang** [comment]
If you or your university is interested to try out Intel's 3rd Gen. This might help you get some trial access to Intel's latest SW (oneAPI, including TF) & HW (including latest gen Xeon processors): https://intelsoftwaresites.secure.force.com/devcloud/oneapi

**Comment by zhao1157** [comment]
@wei-v-wang Thank you so much for this great link! I will give it a go later.
