### ISSUE TITLE
Possibility of updated MKL docker image on latest 2.4.0

### ISSUE THREAD

**Issue by dcyoung** [IntelAI/models#71]
I've been leveraging the latest tag from dockerhub `intel/intel-optimized-tensorflow-serving:2.3.0-mkl` to deploy some tensorflow GPU models on CPU, which cannot run on vanilla tensorflow cpu. However, for other reasons we must migrate to tensorflow serving 2.4 which was released a month ago.  

Can we expect a newer version of the optimized docker image => `intel/intel-optimized-tensorflow-serving:2.4.0-mkl`? If so is there any eta? 

I've encountered some trouble attempting to build myself. Following this guide https://github.com/IntelAI/models/blob/master/docs/general/tensorflow_serving/InstallationGuide.md with `2.4.0` instead of `2.3.0`, the docker build successfully passes the build of tensorflow serving... but later results in errors when trying to copy the library files:

```bash
cannot stat '/root/.cache/bazel/_bazel_root/*/external/mkl_linux/lib/*': No such file or directory
```
I can't seem to find the produced lib files anywhere in the intermediate containers.

Any insight?

**Comment by ashahba** [comment]
@dcyoung I'm, assigned to work on this ticket which is really just fixing the issue you reported on TensorFlow serving and will keep you posted once I have a fix.

**Comment by ashahba** [comment]
A PR is posted here to fix this issue:
https://github.com/tensorflow/serving/pull/1818
