### ISSUE TITLE
INT8 model source

### ISSUE THREAD

**Issue by AlexKoff88** [IntelAI/models#73]
Hi,

I have a question regarding quantization. How to get a model in 8-bits representation, like [MobileNet v1 INT8](https://github.com/IntelAI/models/tree/master/models/image_recognition/tensorflow/mobilenet_v1/inference/int8)?

Is it possible to convert a model to such representation that was trained with TF Quantization-Aware Training and contains FakeQuantizeWithMinMax nodes?

**Comment by AlexKoff88** [comment]
Can anybody answer my questions?

**Comment by mlukasze** [comment]
Hi @AlexKoff88 , sorry you has to wait.

To use Mobilenet v1 int8 you can simply use out of the [box container](https://software.intel.com/content/www/us/en/develop/articles/containers/mobilenetv1-int8-inference-tensorflow-container.html) or simple [model itself](https://software.intel.com/content/www/us/en/develop/articles/containers/mobilenetv1-int8-inference-tensorflow-model.html).

All other packages are listed [here](https://github.com/IntelAI/models/tree/master/benchmarks).
Please do not hesitate to ask if you will any other questions.

Ad. quantization - please read a documentation of [LPOT](https://github.com/intel/lpot) and contact with team who develops it for more details.

Best regards
Michal

**Comment by AlexKoff88** [comment]
@mlukasze, thanks for the reply!

But if I already have my custom model trained with Tensorflow Quantization-Aware Training. How cat I export it to the INT8 representation that your benchmark can run?

**Comment by mlukasze** [comment]
@AlexKoff88 please start with [LPOT](https://github.com/intel/lpot) and contact with dev team if something will be not explained enough in docs.

**Comment by AlexKoff88** [comment]
ok, thanks.
