### ISSUE TITLE
Add wide&deep model support for Tensorflow Serving？

### ISSUE THREAD

**Issue by 0400H** [IntelAI/models#82]
When I tried to serve the model to [tensorflow serving](https://github.com/tensorflow/serving), but fount it is no support in the [link](https://github.com/IntelAI/models/tree/master/benchmarks)

So I try to write the client and encounter a similar [issue](https://github.com/IntelAI/models/issues/78) after deployed model to tf-serving . 

Are there any plans to add wide&deep model support for tensorflow serving?

**Comment by dmsuehir** [comment]
@0400H  We have a TF serving client for Wide & Deep large dataset here: [run_tf_serving_client.py](https://github.com/IntelAI/models/blob/master/k8s/recommendation/tensorflow/wide_deep_large_ds/training/fp32/run_tf_serving_client.py).

It's used as part of our Kubernetes pipeline that does Wide & Deep large dataset FP32 training (which exports a saved_model.pb) and serves the model, but it should work outside of kubernetes as well if you already have a saved model that you're serving. Does this help?

**Comment by 0400H** [comment]
> @0400H We have a TF serving client for Wide & Deep large dataset here: [run_tf_serving_client.py](https://github.com/IntelAI/models/blob/master/k8s/recommendation/tensorflow/wide_deep_large_ds/training/fp32/run_tf_serving_client.py).
> 
> It's used as part of our Kubernetes pipeline that does Wide & Deep large dataset FP32 training (which exports a saved_model.pb) and serves the model, but it should work outside of kubernetes as well if you already have a saved model that you're serving. Some documentation on running the client can be found [here](https://github.com/IntelAI/models/tree/master/k8s/recommendation/tensorflow/wide_deep_large_ds/training/fp32#tensorflow-serving-client). Does this help?

@dmsuehir 

It has been done through the following link:
[wide_deep](https://github.com/IntelAI/models/tree/master/benchmarks/recommendation/tensorflow/wide_deep)
[wide_deep_fp32_pretrained_model.tar.gz](https://storage.googleapis.com/intel-optimized-tensorflow/models/v1_8/wide_deep_fp32_pretrained_model.tar.gz
)

It also refers to many ancient source codes from other websites, which is really an ugly implementation.

**Comment by sramakintel** [comment]
@0400H: do you still need help with this issue?
